CREATE SCHEMA IF NOT EXISTS public;

-- CREATE TRIGGER
CREATE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE member (
    member_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    gender VARCHAR NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (member_id)
);

CREATE TRIGGER member_set_updated_at
BEFORE UPDATE ON member FOR EACH ROW
EXECUTE PROCEDURE trigger_set_updated_at();

CREATE TABLE _data_migrations (
    version TEXT NOT NULL,
    name TEXT NOT NULL,
    started_at TIMESTAMP(3) NOT NULL,
    finished_at TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (version)
);
