export enum EnumMissionCategory {
  'EMOTIONS' = 'EMOTIONS',
  'UNDERSTANDING' = 'UNDERSTANDING',
  'MEMORIES' = 'MEMORIES',
  'FUTURE' = 'FUTURE',
  'RELATIONSHIP' = 'RELATIONSHIP',
  'PREFERENCES' = 'PREFERENCES',
  'VALUES' = 'VALUES',
  'GROWTH' = 'GROWTH',
  'HUMOR' = 'HUMOR',
  'CHALLENGES' = 'CHALLENGES',
  'FAMILY' = 'FAMILY',
  'ROMANCE' = 'ROMANCE',
}
