export enum EnumMissionCategory {
  'HAPPINESS_N_THANKS' = 'HAPPINESS_N_THANKS',
  'POSITIVE_N_ATTRACTION' = 'POSITIVE_N_ATTRACTION',
  'INFLUENCE_N_CHANGE' = 'INFLUENCE_N_CHANGE',
  'FEAR_N_DIFFICULTY' = 'FEAR_N_DIFFICULTY',
  'DISAPPOINTMENT' = 'DISAPPOINTMENT',
  'CONFLICT_RESOLUTION' = 'CONFLICT_RESOLUTION',
  'EXPECTATION_AND_ROLE' = 'EXPECTATION_AND_ROLE',
  'GROWTH_AND_LEARNING' = 'GROWTH_AND_LEARNING',
}
